# -*- coding: utf-8 -*-
"""Projeto - Automatização Dados Estados do Brasil

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFZwgMDh8s2Bilvwrs2TFf46eg2ct3iR
"""

import pandas as pd
import numpy as np
import datetime

# Importação do dataset
url = "https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv"
dataset = pd.read_csv(url)

# Remoção de colunas "inuteis" para o projeto
dataset = dataset[['epi_week', 'date', 'state','newDeaths', 'deaths', 'newCases', 'totalCases', 'recovered', 'suspects', 'tests']]
# Substituindo os nulos por 0 zeros
dataset = dataset.fillna(int(0))       
# Retirando totas as linhas que contem Total na coluna estado
total = dataset
dataset = dataset.drop(dataset[dataset.state == 'TOTAL'].index)

# Criação da coluna 'semana pandemia'
size = len(dataset)
dataset['Semana Pandemia'] = dataset['epi_week']-8

#Criação coluna Região
sul = 'PR RS SC Sul'.split()
sudeste = 'ES MG RJ SP Sudeste'.split()
centro_oeste = 'DF GO MS MT Centro-Oeste'.split()
norte = 'AC AM AP PA RO RR TO Norte'.split()
nordeste = 'AL BA CE MA PE PI PB RN SE Nordeste'.split()
brasil = [sul, sudeste, centro_oeste, norte, nordeste]
regioes = []

#Criando os dados para a coluna região
for i in dataset['state']:
  for regiao in brasil:
    for estado in regiao:   
        if i == estado:
          regioes.append(regiao[-1])
         # print(regiao[-1], i, estado)

dataset['Região'] = regioes

#Criação coluna Novos Recuperados
by_state = dataset.sort_values(["state", "date"])
novos_recuperados = []
recuperados = list(by_state['recovered'])

for n, i in enumerate(recuperados):
  try:
    novo = int(recuperados[n] - recuperados[n-1])
  except:
    novo = 0
  if novo < 0:
    novo = 0
  novos_recuperados.append(novo)

by_state['Novos Recuperados'] = novos_recuperados

#Alterando os numeros de decimal para inteiro
by_state.recovered = by_state.recovered.astype(int)
by_state.suspects = by_state.suspects.astype(int)
by_state.tests = by_state.tests.astype(int)
dataset = by_state.sort_index()

#Alterando formato das datas
datas = list(dataset["date"])
novas_datas = []
for dia in datas:
  dia = dia.split("-")
  dia = "/".join(dia[::-1])
  novas_datas.append(dia)

dataset["date"] = novas_datas

#substituindo valores negativos
def negativo(n):
  if n < 0:
    return 0
  return n
dataset['newCases']=dataset['newCases'].apply(negativo)
dataset['newDeaths']=dataset['newDeaths'].apply(negativo)

#Alterando a ordem das colunas
#['epi_week', 'date', 'state', 'newDeaths', 'deaths', 'newCases','totalCases', 'recovered', 'suspects', 'tests', 'Semana Pandemia', 'Região']
dataset = dataset[['date', 'Região', 'state', 'epi_week', 'Semana Pandemia', 'newDeaths', 'deaths', 'newCases', 'totalCases', 'Novos Recuperados', 'recovered', 'suspects', 'tests']]

#Mudando o nome das colunas
dataset = dataset.rename(columns={'epi_week': 'Semana Ano', 'date': 'Data', 'state':'Estado', 'newDeaths':'Novos Óbitos', 'deaths':'Óbitos', 'newCases':'Novos Casos', 'totalCases':'Total Casos', 'recovered':'Recuperados', 'suspects':'Suspeitos', 'tests':'Testes'})

dataset.tail(50)

#Criando o arquivo
dataset.to_excel("/content/Covid 19 - Estados do Brasil.xlsx", sheet_name='Covid 19 - Estados do Brasil', index=False)

  #Função de download
from google.colab import files
files.download('Covid 19 - Estados do Brasil.xlsx')

#HOTFIX
total.drop(total[total.state != 'TOTAL'].index, inplace=True)
total.tail()

